name: MPPL

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
      - name: add fonts
        run: |
          sudo apt-get install ttf-mscorefonts-installer
          sudo apt-get install fontconfig
          fc-list :lang=zh
          ls -lh /usr/share/fonts/
          cp -rf ./fonts/* /usr/share/fonts/
          mkfontscale
          mkfontdir
          fc-cache
          fc-list
      - name: install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full
          sudo apt-get install pandoc
          # cabal update
          # cabal install pandoc
          # sudo apt-get install latex-cjk-chinese
          # sudo apt-get install xzdec
          # sudo tlmgr init-usertree
          # sudo tlmgr install framed
          # sudo tlmgr install titling
          sudo apt-get clean
      - name: build pdf
        run: |
          pandoc -f  markdown-auto_identifiers  --listings --latex-engine=xelatex --template=./templates/mppl.tex  --output=./output/RISC-V指令集手册-中文.pdf ./src/*.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
