name: MPPL

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          mkdir output  # create output dir
      - uses: docker://pandoc/latex:2.9
        with:
          args: -f  markdown-auto_identifiers  --listings --pdf-engine=xelatex --template=./templates/mppl.tex  --output=./output/RISC-V指令集手册-中文.pdf ./src/*.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
