name: MPPL

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          # sudo apt-get update
          sudo apt-get install texlive-latex-base
          sudo apt-get install latex-cjk-chinese
          sudo apt-get install xzdec
          tlmgr init-usertree
          tlmgr install framed
          tlmgr install titling
          apt-get clean
          rm -rf /var/lib/apt/lists/*
          mkdir output  # create output dir
      - uses: docker://pandoc/latex:2.9
        with:
          args: -f  markdown-auto_identifiers  --listings --pdf-engine=xelatex --template=/github/workspace/templates/mppl.tex  --output=./output/RISC-V指令集手册-中文.pdf /github/workspace/src/Chapter1-Introduction.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
